### ISSUE TITLE
I don't understand the caching logic

### ISSUE THREAD

**Issue by nrser** [spk/money-open-exchange-rates#38]
I'm reading through the code, and it seems like the only thing that calls `store_in_cache` is `save_rates`... and nothing call that? Meaning that after the gem fetches data from the OXR API it *doesn't cache it*?

I feel like I must be missing something because that doesn't make any sense to me... after you've paid the cost of the API hit why would you not want to cache the results?

**Comment by spk** [comment]
Hi, yes `store_in_cache` is a protected method used on public method `save_rates`.
This have to be used with public method `update_rates` (on crontab or anything else to fetch new data depending on `ttl_in_seconds` option, so the data is updated and then not query each time from OXR API.
Hope its clear

**Comment by kuboon** [comment]
Once the response JSON is saved in cache, it looks never expire even if I set `ttl_in_seconds`.

`get_rate` calls `expire_rates`.
When the cache is expired, `update_rates` is called.
`update_rates` method calls `read_from_cache`.

**Comment by kuboon** [comment]
another problem:
if I call `get_rate(:JPY, :EUR)` with `source` currency is USD, `calc_pair_rate_using_base` is called and the rate is saved to the store.
Next time, `get_rate(:JPY, :EUR)` gets the rate from the store. It ignores refreshed JPY/USD rate.

**Comment by JasonBarnabe** [comment]
I would also like to express the opinion that the caching doesn't make sense. As best as I can tell:

- `update_rates`: reads from cache if present (with no check on expiry), reads from API otherwise (and does not store in cache!)
- `save_rates`: reads from API, stores in cache
- `expire_rates`: checks if the rates have expired (using an in-memory value rather than one stored in cache). If the rates are "expired", calls `update_rates` and changes the expiry date.
- Things like the money gem will call `get_rate`, which calls `expire_rates` before looking things up.

I suggest the following improvements:

1. Any times the rates are read from the API successfully, they should be stored in the cache.
2. The expiration time of the cache should be based only on the time it was last loaded. When you set `ttl_in_seconds` (on app startup), it's being set to current time + TTL, even if the rates were previously loaded in the cache.

**Comment by JasonBarnabe** [comment]
This is what I'm working with to try to solve the above, along with preventing the test environment from using up all the monthly requests.

```ruby
require 'money'
require 'money/bank/open_exchange_rates_bank'

module Money::Bank
  class BetterCachingRatesBank < OpenExchangeRatesBank

    CACHE_KEY = 'oxr-rates'

    def read_from_url
      if Rails.env.test?
        text = File.read('spec/data/json/exchange_rates/data.json')
      else
        text = super
      end
      store_in_cache(text) if valid_rates?(text)
      return text
    end

    def store_in_cache(text)
      Rails.cache.write(CACHE_KEY, text, expires_in: 2.days, race_condition_ttl: 10)
    end

    def read_from_cache
      Rails.cache.read(CACHE_KEY)
    end
  end
end

oxr = Money::Bank::BetterCachingRatesBank.new
oxr.app_id = Secrets.openexchangerates['api_key'] unless Rails.env.test?
oxr.update_rates

Money.default_bank = oxr
```

**Comment by renata-ssg** [comment]
@JasonBarnabe thank you so much for your solution.  I was banging my head against the wall wondering why caching wasn't working after I'd blown through the monthly request limit in a day. You saved me a bunch of time.

**Comment by spk** [comment]
Ok I could get the problem everyone facing with @JasonBarnabe snippet; https://github.com/spk/money-open-exchange-rates/pull/42 should fix the problem everyone facing with the caching, let me know what do all think

**Comment by JasonBarnabe** [comment]
This looks like it would solve the main problem where the loaded rates are not saved to the cache automatically.

I still think the TTL setting can cause confusion because the cache will likely also have a TTL. I think this should at least be documented, perhaps with a suggestion that if you have a "fast" cache, you don't set TTL on OXR at all.

**Comment by spk** [comment]
Documentation updated in https://github.com/spk/money-open-exchange-rates/pull/42/commits/43121875466faad3f9887d0d9574320b58b514f4

**Comment by spk** [comment]
Improvements released in [v1.0.0](https://github.com/spk/money-open-exchange-rates/releases/tag/v1.0.0)

**Comment by spk** [comment]
See also [v1.1.0](https://github.com/spk/money-open-exchange-rates/releases/tag/v1.1.0) feel free to open other issues

**Comment by spk** [comment]
Please update to [1.2.0](https://github.com/spk/money-open-exchange-rates/releases/tag/v1.2.0) instead 1.1.0 introduce a issue on fetching rates on expire per default
